org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84
curios_version=15.0.0+26.1.2
jei_version=29.20.0.58

## Mod Properties
mod_id=noblephantasms
mod_name=Noble Phantasms
mod_license=MIT License
mod_version=0.0.1-26.1.2
mod_group_id=net.turtleboi.noblephantasms
